version: '3'
services:
  taiko-web-server:
    build: .
    environment:
      PORT: 8080
    ports:
      - '8199:8080'
    volumes:
      - './db/taiko.db:/srv/taiko-web/taiko.db'
      - './songs:/srv/taiko-web/public/songs'
      - './etc/config.json:/srv/taiko-web/config.json'
